module.exports = Object.freeze({
    DEFAULT_LANGUAGE_KEY: 'DEFAULT_LANGUAGE',
    DEFAULT_LAST_NEWS_TO_RETRIEVE_KEY: 'DEFAULT_LAST_NEWS_TO_RETRIEVE',
    MAX_LAST_NEWS_TO_RETRIEVE_KEY: 'MAX_LAST_NEWS_TO_RETRIEVE',
    NEWS_DYNAMO_DB_TABLE_NAME_KEY: 'NEWS_DYNAMO_DB_TABLE_NAME'
});